/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/AliyunContainerService/et-operator/apis/et/v1alpha1"
	scheme "github.com/AliyunContainerService/et-operator/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrainingJobSpecsGetter has a method to return a TrainingJobSpecInterface.
// A group's client should implement this interface.
type TrainingJobSpecsGetter interface {
	TrainingJobSpecs(namespace string) TrainingJobSpecInterface
}

// TrainingJobSpecInterface has methods to work with TrainingJobSpec resources.
type TrainingJobSpecInterface interface {
	Create(*v1alpha1.TrainingJobSpec) (*v1alpha1.TrainingJobSpec, error)
	Update(*v1alpha1.TrainingJobSpec) (*v1alpha1.TrainingJobSpec, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TrainingJobSpec, error)
	List(opts v1.ListOptions) (*v1alpha1.TrainingJobSpecList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TrainingJobSpec, err error)
	TrainingJobSpecExpansion
}

// trainingJobSpecs implements TrainingJobSpecInterface
type trainingJobSpecs struct {
	client rest.Interface
	ns     string
}

// newTrainingJobSpecs returns a TrainingJobSpecs
func newTrainingJobSpecs(c *EtV1alpha1Client, namespace string) *trainingJobSpecs {
	return &trainingJobSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trainingJobSpec, and returns the corresponding trainingJobSpec object, and an error if there is any.
func (c *trainingJobSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.TrainingJobSpec, err error) {
	result = &v1alpha1.TrainingJobSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrainingJobSpecs that match those selectors.
func (c *trainingJobSpecs) List(opts v1.ListOptions) (result *v1alpha1.TrainingJobSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TrainingJobSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trainingJobSpecs.
func (c *trainingJobSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a trainingJobSpec and creates it.  Returns the server's representation of the trainingJobSpec, and an error, if there is any.
func (c *trainingJobSpecs) Create(trainingJobSpec *v1alpha1.TrainingJobSpec) (result *v1alpha1.TrainingJobSpec, err error) {
	result = &v1alpha1.TrainingJobSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		Body(trainingJobSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a trainingJobSpec and updates it. Returns the server's representation of the trainingJobSpec, and an error, if there is any.
func (c *trainingJobSpecs) Update(trainingJobSpec *v1alpha1.TrainingJobSpec) (result *v1alpha1.TrainingJobSpec, err error) {
	result = &v1alpha1.TrainingJobSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		Name(trainingJobSpec.Name).
		Body(trainingJobSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the trainingJobSpec and deletes it. Returns an error if one occurs.
func (c *trainingJobSpecs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trainingJobSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trainingjobspecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched trainingJobSpec.
func (c *trainingJobSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TrainingJobSpec, err error) {
	result = &v1alpha1.TrainingJobSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trainingjobspecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
